import { createBoard, DIFFICULTIES, progress } from "./minesweeper.js";
import { applyEvent, createSession } from "./session.js";
const api = window.lanchat, $ = (id) => document.getElementById(id); let room = null, session = null, boardPeerId = null, counter = 0;
$("refreshRooms").onclick = refresh; $("createRoom").onclick = createRoom; $("startButton").onclick = start; $("leaveButton").onclick = leave;
if (api) { api.events.onPluginEnter(refresh); api.events.onRoomEvent(onEvent); api.events.onThemeChanged(applyTheme); Promise.all([api.theme.current().then(applyTheme), refresh()]).catch(report); } else $("statusText").textContent = "请从 LanChat 插件中心打开";
async function refresh() { if (!api) return; const rooms = await api.rooms.list({ gameId: "minesweeper" }); $("roomList").replaceChildren(...rooms.map(roomCard)); if (!rooms.length) $("roomList").textContent = "暂无房间，可以创建单机局"; }
function roomCard(value) { const card = document.createElement("article"), copy = document.createElement("div"), title = document.createElement("strong"), meta = document.createElement("small"), button = document.createElement("button"); title.textContent = value.name || "扫雷竞速"; meta.textContent = `${value.memberPeerIds.length}/6 人`; copy.append(title, meta); button.textContent = "加入"; button.onclick = () => join(value.roomId); card.append(copy, button); return card; }
async function createRoom() { room = await api.rooms.create({ gameId: "minesweeper", name: $("roomName").value.trim() || "扫雷竞速", maxPlayers: 6, schemaVersion: 1 }); boardPeerId = room.ownerPeerId; session = createSession(room.roomId, room.ownerPeerId, room.memberPeerIds, selectedDifficulty()); render(); refresh(); }
async function join(roomId) { room = await api.rooms.join({ roomId }); session = await api.rooms.snapshot({ roomId }).catch(() => null) || createSession(room.roomId, room.ownerPeerId, room.memberPeerIds, selectedDifficulty()); boardPeerId = room.memberPeerIds.at(-1); render(); }
async function leave() { if (room) await api.rooms.leave({ roomId: room.roomId }); room = session = boardPeerId = null; render(); refresh(); }
function start() { if (!room) return createRoom().then(start); send("minesweeper.start", { ...selectedDifficulty(), seed: Date.now() }); }
function selectedDifficulty() { return DIFFICULTIES.find((item) => item.key === $("difficulty").value) ?? DIFFICULTIES[1]; }
async function send(type, payload) { if (room) await api.rooms.send({ roomId: room.roomId, type, payload, idempotencyKey: `${room.roomId}-${Date.now()}-${counter += 1}` }).catch(report); }
function onEvent(event) { if (!room || event.roomId !== room.roomId || event.gameId !== "minesweeper") return; session = applyEvent(session, event); boardPeerId = event.senderPeerId; render(); const player = session.players[event.senderPeerId]; if (player?.won) api.leaderboard.submit({ gameId: "minesweeper", roomId: room.roomId, idempotencyKey: `${room.roomId}-result-${event.senderPeerId}-${event.sequence}`, result: { peerId: event.senderPeerId, elapsedMs: player.elapsedMs, moves: player.moves, ...session.settings } }).catch(report); }
function interact(event, x, y, type = "minesweeper.reveal") { event.preventDefault(); if (session?.phase === "playing") send(type, { x, y }); }
function render() { const settings = session?.settings ?? selectedDifficulty(), player = session?.players[boardPeerId] ?? null, board = player?.board ?? createBoard({ ...settings, seed: 1 }), stats = player?.progress ?? progress(board); $("roomMeta").textContent = room ? `房间 ${room.roomId.slice(0, 8)} · ${room.memberPeerIds.length}/6 人` : "可以单人创建房间"; $("statusText").textContent = !session ? "选择难度后开始" : session.phase === "lobby" ? "等待开始" : session.phase === "ended" ? `玩家 ${session.winnerPeerId} 完成` : player?.lost ? "踩雷了，等待本局结束" : "竞速进行中"; $("progress").textContent = `${stats.revealedSafe} / ${stats.totalSafe} · 🚩${stats.flagged}`; $("board").style.setProperty("--cols", settings.width); $("board").replaceChildren(...board.flatMap((row, y) => row.map((cell, x) => { const b = document.createElement("button"); b.className = `cell${cell.revealed ? " revealed" : ""}${cell.exploded ? " exploded" : ""}`; b.textContent = cell.flagged ? "🚩" : cell.revealed && cell.mine ? "💣" : cell.revealed && cell.adjacent ? String(cell.adjacent) : ""; b.dataset.number = String(cell.adjacent); b.onclick = (e) => interact(e, x, y); b.oncontextmenu = (e) => interact(e, x, y, "minesweeper.flag"); b.ondblclick = (e) => interact(e, x, y, "minesweeper.chord"); return b; }))); }
function applyTheme(theme) { document.documentElement.dataset.theme = theme.mode; for (const [k, v] of Object.entries(theme.tokens ?? {})) document.documentElement.style.setProperty(`--${k}`, v); }
function report(error) { api?.logger.error("扫雷插件操作失败", { message: String(error) }); api?.ui.notify({ title: "扫雷竞速", body: String(error), level: "error" }); }
render();
