import { createBoard, pieceLabel } from "./xiangqi.js";
import { applyEvent, createSession } from "./session.js";
const api = window.lanchat, $ = (id) => document.getElementById(id);
let room = null, session = null, selected = null, counter = 0;
for (const [id, fn] of [["refreshRooms", refresh], ["createRoom", createRoom], ["readyButton", () => send("xiangqi.ready", { ready: true })], ["startButton", () => send("xiangqi.start", {})], ["resignButton", () => send("xiangqi.resign", {})], ["restartButton", () => send("xiangqi.restart", {})], ["inviteButton", () => room && api.rooms.invite({ roomId: room.roomId }).catch(report)], ["leaveButton", leave]]) $(id).addEventListener("click", fn);
if (api) { api.events.onPluginEnter((context) => { const payload = context?.payload; if (payload?.action === "join" && payload.roomId) join(payload.roomId).catch(report); else refresh(); }); api.events.onRoomEvent(onEvent); api.events.onThemeChanged(applyTheme); Promise.all([api.theme.current().then(applyTheme), refresh()]).catch(report); } else $("statusText").textContent = "请从 LanChat 插件中心打开";
async function refresh() { if (!api) return; const rooms = await api.rooms.list({ gameId: "xiangqi" }); $("roomList").replaceChildren(...rooms.map(roomCard)); if (!rooms.length) $("roomList").textContent = "还没有象棋房间"; }
function roomCard(value) { const card = document.createElement("article"), copy = document.createElement("div"), title = document.createElement("strong"), meta = document.createElement("small"), button = document.createElement("button"); title.textContent = value.name || "象棋对局"; meta.textContent = `${value.memberPeerIds.length}/2 人`; copy.append(title, meta); button.textContent = "加入"; button.onclick = () => join(value.roomId); card.append(copy, button); return card; }
async function createRoom() { room = await api.rooms.create({ gameId: "xiangqi", name: $("roomName").value.trim() || "象棋对局", maxPlayers: 2, schemaVersion: 1 }); session = createSession(room.roomId, room.ownerPeerId, room.memberPeerIds); render(); refresh(); }
async function join(roomId) { room = await api.rooms.join({ roomId }); session = await api.rooms.snapshot({ roomId }).catch(() => null) || createSession(room.roomId, room.ownerPeerId, room.memberPeerIds); render(); }
async function leave() { if (room) await api.rooms.leave({ roomId: room.roomId }); room = session = selected = null; render(); refresh(); }
async function send(type, payload) { if (room) await api.rooms.send({ roomId: room.roomId, type, payload, idempotencyKey: `${room.roomId}-${Date.now()}-${counter += 1}` }).catch(report); }
function onEvent(event) { if (!room || event.roomId !== room.roomId || event.gameId !== "xiangqi") return; session = applyEvent(session, event); selected = null; render(); if (session.phase === "ended") api.leaderboard.submit({ gameId: "xiangqi", roomId: room.roomId, idempotencyKey: `${room.roomId}-result-${event.sequence}`, result: { winnerPeerId: session.winnerPeerId } }).catch(report); }
function clickCell(x, y) { if (!session || session.phase !== "playing") return; const piece = session.board[y][x]; if (!selected && piece?.side === session.currentSide) selected = { x, y }; else if (selected) { send("xiangqi.move", { from: selected, to: { x, y } }); selected = null; } render(); }
function render() { $("roomMeta").textContent = room ? `房间 ${room.roomId.slice(0, 8)} · ${room.memberPeerIds.length}/2 人` : "尚未进入房间"; $("statusText").textContent = !session ? "选择或创建房间" : session.phase === "lobby" ? "等待双方准备" : session.phase === "ended" ? `玩家 ${session.winnerPeerId ?? "-"} 获胜` : `轮到${session.currentSide === "red" ? "红方" : "黑方"}`; const board = session?.board ?? createBoard(); $("board").replaceChildren(...board.flatMap((row, y) => row.map((piece, x) => { const b = document.createElement("button"); b.className = `cell${selected?.x === x && selected?.y === y ? " selected" : ""}`; if (piece) { const p = document.createElement("span"); p.className = `piece ${piece.side}`; p.textContent = pieceLabel(piece); b.append(p); } b.onclick = () => clickCell(x, y); return b; }))); }
function applyTheme(theme) { document.documentElement.dataset.theme = theme.mode; for (const [k, v] of Object.entries(theme.tokens ?? {})) document.documentElement.style.setProperty(`--${k}`, v); }
function report(error) { api?.logger.error("象棋插件操作失败", { message: String(error) }); api?.ui.notify({ title: "中国象棋", body: String(error), level: "error" }); }
render();
