import{cardLabel,createBoard,godLabel,levelName,propertyToll,tileName}from"./monopoly.js";import{applyEvent,createSession}from"./session.js";
const api=window.lanchat,$=id=>document.getElementById(id);let room=null,session=null,localPeerId=null,counter=0,zoom=1,view="3d";
const actions={refreshRooms:refresh,createRoom,addBotButton:()=>send("monopoly.add_bot",{}),readyButton:()=>send("monopoly.ready",{ready:true}),startButton:()=>send("monopoly.start",{seed:Date.now(),startingCoins:5000,maxRounds:20}),rollButton:()=>send("monopoly.roll",{values:[dice(),dice()]}),buyButton:()=>send("monopoly.buy",{buy:true}),skipButton:()=>send("monopoly.buy",{buy:false}),restartButton:()=>send("monopoly.restart",{}),leaveButton:leave,sendChat:sendChat,rulesButton:()=>$("rules").showModal(),closeRules:()=>$("rules").close(),flatView:()=>setView("flat"),threeView:()=>setView("3d"),zoomIn:()=>setZoom(zoom+.1),zoomOut:()=>setZoom(zoom-.1),resetZoom:()=>setZoom(1)};for(const[id,fn]of Object.entries(actions))$(id).onclick=fn;$("chatInput").onkeydown=e=>{if(e.key==="Enter")sendChat();};
if(api){api.events.onPluginEnter(refresh);api.events.onRoomEvent(onEvent);api.events.onThemeChanged(theme);Promise.all([api.theme.current().then(theme),refresh()]).catch(report);}else $("banner").textContent="请从 LanChat 插件中心打开";
async function refresh(){if(!api)return;const rooms=await api.rooms.list({gameId:"monopoly"});$("roomList").replaceChildren(...rooms.map(roomCard));if(!rooms.length)$("roomList").textContent="还没有大富翁房间";}
function roomCard(value){const card=document.createElement("article"),copy=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("small"),button=document.createElement("button");title.textContent=value.name||"大富翁房间";meta.textContent=`${value.memberPeerIds.length}/4 人`;copy.append(title,meta);button.textContent="加入";button.onclick=()=>join(value.roomId);card.append(copy,button);return card;}
async function createRoom(){room=await api.rooms.create({gameId:"monopoly",name:$("roomName").value.trim()||"大富翁房间",maxPlayers:4,schemaVersion:1});localPeerId=room.ownerPeerId;session=createSession(room.roomId,room.ownerPeerId,room.memberPeerIds);render();refresh();}
async function join(roomId){room=await api.rooms.join({roomId});localPeerId=room.memberPeerIds.at(-1);session=await api.rooms.snapshot({roomId}).catch(()=>null)||createSession(room.roomId,room.ownerPeerId,room.memberPeerIds);render();}
async function leave(){if(room)await api.rooms.leave({roomId:room.roomId});room=session=localPeerId=null;render();refresh();}
async function send(type,payload){if(room)await api.rooms.send({roomId:room.roomId,type,payload,idempotencyKey:`${room.roomId}-${Date.now()}-${counter+=1}`}).catch(report);}
function sendChat(){const content=$("chatInput").value.trim();if(content){send("monopoly.chat",{content});$("chatInput").value="";}}
function onEvent(event){if(!room||event.roomId!==room.roomId||event.gameId!=="monopoly")return;session=applyEvent(session,event);render();if(session.phase==="ended")api.leaderboard.submit({gameId:"monopoly",roomId:room.roomId,idempotencyKey:`${room.roomId}-result-${event.sequence}`,result:{winnerPeerId:session.game.winnerId,players:session.game.players.map(p=>({peerId:p.peerId,coins:p.coins,isBot:p.isBot}))}}).catch(report);}
function render(){renderBoard();renderPlayers();const game=session?.game;$("turnInfo").textContent=game?`第 ${game.round} / ${game.maxRounds} 回合`:"第 1 / 20 回合";const current=game?.players.find(p=>p.peerId===game.currentPlayerId);$("currentPlayer").textContent=current?`当前行动：${current.nickname} · ${current.coins} 金币`:"尚未开始";$("banner").textContent=game?.logs.at(-1)??"等待玩家加入";$("logs").replaceChildren(...(game?.logs??[]).slice(-30).reverse().map(text=>{const p=document.createElement("p");p.title=text;p.textContent=text;return p;}));renderCards(current);renderChat();const pending=game?.pending?.playerId===localPeerId;$("buyButton").hidden=!pending||game.pending.kind!=="buy";$("skipButton").hidden=!pending||game.pending.kind!=="buy";}
function renderBoard(){const game=session?.game,board=game?.board??createBoard();$("board").replaceChildren(...board.map(tile=>{const el=document.createElement("button"),pos=position(tile.index);el.className=`tile ${tile.kind} side-${pos.side}`;el.style.setProperty("--x",pos.x);el.style.setProperty("--y",pos.y);el.title=tileName(tile);const property=game?.properties[tile.index];if(tile.kind==="corner"){const art=document.createElement("i");art.className=`corner-art ${tile.corner}`;el.append(art);}else if(tile.kind==="event"){const img=document.createElement("img");img.src="./assets/events/slot-machine.png";el.append(img);}else{const building=document.createElement("i");building.className=`building level-${property?.level??0}`;building.style.setProperty("--variant",String(property?.variant??0));building.style.setProperty("--owner-row",`${ownerIndex(game,property?.ownerId)*50}%`);el.append(building);if(property?.ownerId){const edge=document.createElement("span");edge.className="owner-edge";edge.style.setProperty("--owner",game.players.find(p=>p.peerId===property.ownerId)?.color??"#aaa");edge.innerHTML="<b></b><b></b><b></b>";edge.dataset.level=String(property.level);el.append(edge);}if(property?.level){const toll=document.createElement("em");toll.className="toll";toll.textContent=String(propertyToll(property));el.append(toll);if(property.tollMultiplier>1){const badge=document.createElement("span");badge.className="multiplier";badge.textContent=`🪙×${property.tollMultiplier}`;el.append(badge);}}}const label=document.createElement("span");label.className="tile-name";label.textContent=tileName(tile);el.append(label);for(const token of game?.godTokens.filter(g=>g.index===tile.index)??[]){const mark=document.createElement("i");mark.className=`god ${token.god}`;mark.title=godLabel(token.god);el.append(mark);}for(const player of game?.players.filter(p=>p.position===tile.index&&!p.eliminated)??[]){const token=document.createElement("i"),tone=ownerIndex(game,player.peerId);token.className="player-token";token.style.setProperty("--portrait-x",`${tone*33.333}%`);token.style.setProperty("--color",player.color);token.title=player.nickname;el.append(token);}el.onclick=()=>{if(game?.pending?.kind==="airport"&&game.pending.playerId===localPeerId)send("monopoly.airport",{index:tile.index});};return el;}));}
function renderPlayers(){const seats=session?.seats??[],$list=$("players");$list.replaceChildren(...seats.map((seat,i)=>{const player=session?.game.players.find(p=>p.peerId===seat.peerId),card=document.createElement("article");card.className=`player-card${session?.game.currentPlayerId===seat.peerId?" active":""}${player?.jailTurns?" jailed":""}`;card.style.setProperty("--color",player?.color??"#9aa");card.innerHTML=`<i style="--portrait-x:${i*33.333}%"></i><div><strong>${seat.nickname}${seat.isBot?" · 机器人":""}</strong><small>${seat.ready?"已准备":"等待准备"}</small><b>${player?.coins??5000} 金币</b></div>${player?.jailTurns?"<span class=chain>⛓</span>":""}`;return card;}));}
function renderCards(current){const root=$("cards");root.replaceChildren(...(current?.peerId===localPeerId?current.cards:[]).map(card=>{const b=document.createElement("button");b.textContent=cardLabel(card);b.onclick=()=>useQuickCard(card,current);return b;}));}
function useQuickCard(card,player){const next=session.game.players.find(p=>p.peerId!==player.peerId&&!p.eliminated)??player,owned=Object.values(session.game.properties).find(p=>p.ownerId===player.peerId);const target=card==="roadblock"?{index:(player.position+3)%40}:card==="double"?{index:owned?.index}:card==="fixed_dice"?{dice:6}:{playerId:next.peerId};send("monopoly.card",{card,target});}
function renderChat(){const list=$("chatList");list.replaceChildren(...(session?.chat??[]).map(msg=>{const p=document.createElement("p");p.className=msg.senderPeerId===localPeerId?"mine":"";p.textContent=`${msg.senderPeerId.slice(0,6)}：${msg.content}`;return p;}));list.scrollTop=list.scrollHeight;}
function position(index){if(index<=10)return{x:10-index,y:10,side:"bottom"};if(index<=20)return{x:0,y:20-index,side:"left"};if(index<=30)return{x:index-20,y:0,side:"top"};return{x:10,y:index-30,side:"right"};}function ownerIndex(game,id){return Math.max(0,game?.players.findIndex(p=>p.peerId===id)??0);}function dice(){return Math.floor(Math.random()*6)+1;}function setView(next){view=next;$("boardStage").className=`board-stage view-${view}`;$("flatView").classList.toggle("active",view==="flat");$("threeView").classList.toggle("active",view==="3d");}function setZoom(value){zoom=Math.max(.65,Math.min(1.5,value));$("board").style.setProperty("--zoom",zoom);$("zoomValue").textContent=`${Math.round(zoom*100)}%`;}function theme(value){document.documentElement.dataset.theme=value.mode;for(const[k,v]of Object.entries(value.tokens??{}))document.documentElement.style.setProperty(`--${k}`,v);}function report(error){api?.logger.error("大富翁插件操作失败",{message:String(error)});api?.ui.notify({title:"大富翁",body:String(error),level:"error"});}render();setView("3d");
