export const BOARD_SIZE=40;
export const ECONOMY={purchase:350,houseRent:500,level2Rent:1000,level3Rent:2000,startReward:1000};
export const PLAYER_COLORS=["#ef5350","#42a5f5","#66bb6a","#ab47bc"];
const CORNERS={0:"start",10:"airport",20:"price_double",30:"jail"},EVENTS=new Set([5,15,25,35]);
const CITIES=["晴川城","云港城","星湖城","青禾城","海棠城","银杏城","望舒城","松风城","锦澜城","北辰城","秋水城","栖霞城","鹭岛城","琥珀城","长乐城","临川城","镜海城","雾凇城","白沙城","南风城","霁月城","澄湾城","鹿鸣城","扶光城","丹枫城","青岚城","流萤城","云栖城","千帆城","玉衡城","春晖城","星野城"];
export const GODS=["wealth","poverty","angel","devil"],CARDS=["roadblock","stay","double","fixed_dice","reverse","frame"];
export function createBoard(){let city=0;return Array.from({length:BOARD_SIZE},(_,index)=>CORNERS[index]?{index,kind:"corner",corner:CORNERS[index]}:EVENTS.has(index)?{index,kind:"event"}:{index,kind:"property",district:Math.floor(index/5),name:CITIES[city++]});}
export function tileName(tile){if(tile.kind==="property")return tile.name;if(tile.kind==="event")return"随机事件";return{start:"起点",airport:"飞机场",price_double:"地价翻倍",jail:"监狱"}[tile.corner];}
export function createGame(players,{startingCoins=5000,maxRounds=20,seed=Date.now()}={}){const board=createBoard(),properties={};for(const tile of board)if(tile.kind==="property")properties[tile.index]={index:tile.index,ownerId:null,level:0,variant:Math.floor(randomOf(seed+tile.index)()*3),tollMultiplier:1,sealedTurns:0};return{board,properties,players:players.slice(0,4).map((p,i)=>({...p,color:PLAYER_COLORS[i],coins:startingCoins,position:0,direction:1,jailTurns:0,stayTurns:0,turtleTurns:0,god:null,godTurns:0,cards:[...CARDS.slice(0,3)],eliminated:false})),roadblocks:[],godTokens:[],currentPlayerId:players[0]?.peerId??null,round:1,maxRounds,startingCoins,pending:null,lastDice:null,logs:["大富翁对局已经准备"],ended:false,winnerId:null};}
export const cloneGame=(state)=>structuredClone(state);
export function rollDice(state,playerId,values=[1,1],random=Math.random){if(state.ended||state.currentPlayerId!==playerId||state.pending)return state;const next=cloneGame(state),player=next.players.find(p=>p.peerId===playerId);if(!player)return state;if(player.jailTurns>0){player.jailTurns-=1;next.logs.push(`${player.nickname}仍在监狱，剩余 ${player.jailTurns} 回合`);return advanceTurn(next);}let total=values.reduce((a,b)=>a+b,0);if(player.forcedDice){total=player.forcedDice;values=[total];delete player.forcedDice;}if(player.turtleTurns>0){total=1;values=[1];player.turtleTurns-=1;}if(player.stayTurns>0){total=0;values=[0];player.stayTurns-=1;}const previous=player.position,target=walkTarget(next,player,total);if(player.direction>0&&target<previous||player.direction<0&&target>previous){player.coins+=ECONOMY.startReward;next.logs.push(`${player.nickname}经过起点，获得 ${ECONOMY.startReward} 金币`);}player.position=target;next.lastDice={playerId,values,total};next.logs.push(`${player.nickname}${total?`前进了 ${total} 格`:"使用停留卡原地停留"}，到达${tileName(next.board[target])}`);collectGod(next,player);settle(next,player,random);return next.pending?next:advanceTurn(next);}
function walkTarget(state,player,steps){let position=player.position;for(let i=0;i<steps;i+=1){position=(position+player.direction+BOARD_SIZE)%BOARD_SIZE;const block=state.roadblocks.findIndex(item=>item.index===position);if(block>=0){state.roadblocks.splice(block,1);state.logs.push(`${player.nickname}撞上路障，停在${tileName(state.board[position])}`);break;}}return position;}
function settle(state,player,random){const tile=state.board[player.position];if(tile.kind==="property"){const property=state.properties[tile.index];if(player.god==="angel"&&property.level<3){property.level+=1;state.logs.push(`天使帮助${player.nickname}将${tile.name}升级为${levelName(property.level)}`);}else if(player.god==="devil"&&property.level>0){property.level-=1;state.logs.push(`恶魔将${tile.name}降级为${levelName(property.level)}`);}if(!property.ownerId){state.pending={kind:"buy",playerId:player.peerId,index:tile.index};return;}if(property.ownerId===player.peerId){if(property.level<3){property.level+=1;state.logs.push(`${player.nickname}将${tile.name}升级为${levelName(property.level)}`);}return;}const owner=state.players.find(p=>p.peerId===property.ownerId);if(!owner||owner.jailTurns>0||property.sealedTurns>0||player.god==="wealth")return;let toll=propertyToll(property);if(player.god==="poverty")toll*=2;const paid=Math.min(player.coins,toll);player.coins-=paid;owner.coins+=paid;state.logs.push(`${player.nickname}向${owner.nickname}支付${tile.name}过路费 ${paid}`);if(player.coins<=0){player.eliminated=true;state.logs.push(`${player.nickname}破产`);}return;}
  if(tile.kind==="event"){const outcomes=["subsidy","maintenance","card","god"],event=outcomes[Math.floor(random()*outcomes.length)];if(event==="subsidy"){player.coins+=800;state.logs.push(`${player.nickname}获得城市补贴 800`);}else if(event==="maintenance"){player.coins=Math.max(0,player.coins-500);state.logs.push(`${player.nickname}支付维护费 500`);}else if(event==="card"){player.cards.push(CARDS[Math.floor(random()*CARDS.length)]);state.logs.push(`${player.nickname}从摇奖机获得一张道具卡`);}else spawnGod(state,random);return;}
  if(tile.corner==="airport"){state.pending={kind:"airport",playerId:player.peerId,index:tile.index};return;}if(tile.corner==="price_double"){const owned=Object.values(state.properties).filter(p=>p.ownerId===player.peerId);if(owned.length){const property=owned[Math.floor(random()*owned.length)];property.tollMultiplier=Math.min(3,property.tollMultiplier+1);state.logs.push(`${tileName(state.board[property.index])}地价变为 ×${property.tollMultiplier}`);}return;}if(tile.corner==="jail"){player.position=30;player.jailTurns=3;state.logs.push(`${player.nickname}被关进监狱 3 回合`);}}
export function buyPending(state,playerId,buy=true){if(state.pending?.kind!=="buy"||state.pending.playerId!==playerId)return state;const next=cloneGame(state),property=next.properties[next.pending.index],player=next.players.find(p=>p.peerId===playerId);if(buy&&player&&player.coins>=ECONOMY.purchase){player.coins-=ECONOMY.purchase;property.ownerId=playerId;property.level=1;next.logs.push(`${player.nickname}购买了${tileName(next.board[property.index])}`);}next.pending=null;return advanceTurn(next);}
export function airportPending(state,playerId,index){if(state.pending?.kind!=="airport"||state.pending.playerId!==playerId||!Number.isInteger(index)||index<0||index>=BOARD_SIZE)return state;const next=cloneGame(state),player=next.players.find(p=>p.peerId===playerId);player.position=index;next.pending=null;next.logs.push(`${player.nickname}乘飞机抵达${tileName(next.board[index])}`);collectGod(next,player);settle(next,player,Math.random);return next.pending?next:advanceTurn(next);}
export function useCard(state,playerId,card,target={}){const next=cloneGame(state),player=next.players.find(p=>p.peerId===playerId),cardIndex=player?.cards.indexOf(card)??-1;if(!player||cardIndex<0||state.currentPlayerId!==playerId)return state;const targetPlayer=next.players.find(p=>p.peerId===target.playerId),property=next.properties[target.index];let used=true;if(card==="roadblock"&&Number.isInteger(target.index))next.roadblocks.push({index:target.index,ownerId:playerId});else if(card==="stay"&&targetPlayer)targetPlayer.stayTurns+=1;else if(card==="double"&&property?.ownerId===playerId)property.tollMultiplier=Math.min(3,property.tollMultiplier+1);else if(card==="fixed_dice"&&Number.isInteger(target.dice)&&target.dice>=1&&target.dice<=12)player.forcedDice=target.dice;else if(card==="reverse"&&targetPlayer)targetPlayer.direction*=-1;else if(card==="frame"&&targetPlayer){targetPlayer.position=30;targetPlayer.jailTurns=3;}else used=false;if(!used)return state;player.cards.splice(cardIndex,1);next.logs.push(`${player.nickname}使用了${cardLabel(card)}`);return next;}
export function propertyToll(property){return [0,ECONOMY.houseRent,ECONOMY.level2Rent,ECONOMY.level3Rent][property.level]*property.tollMultiplier;}
export const levelName=(level)=>["空地","小屋","洋房","地标"][level];
export const cardLabel=(card)=>({roadblock:"路障卡",stay:"停留卡",double:"翻倍卡",fixed_dice:"指定骰子",reverse:"转向卡",frame:"陷害卡"}[card]??card);
export const godLabel=(god)=>({wealth:"财神",poverty:"穷鬼",angel:"天使",devil:"恶魔"}[god]??god);
function collectGod(state,player){const index=state.godTokens.findIndex(g=>g.index===player.position);if(index<0)return;const [token]=state.godTokens.splice(index,1);player.god=token.god;player.godTurns=3;state.logs.push(`${godLabel(token.god)}附身${player.nickname}`);const property=state.properties[player.position];if(property&&token.god==="angel"&&property.level<3)property.level+=1;if(property&&token.god==="devil"&&property.level>0)property.level-=1;}
function spawnGod(state,random){const candidates=state.board.filter(t=>t.kind==="property"&&!state.godTokens.some(g=>g.index===t.index));if(!candidates.length)return;const tile=candidates[Math.floor(random()*candidates.length)],god=GODS[Math.floor(random()*GODS.length)];state.godTokens.push({index:tile.index,god,expiresRound:state.round+2});state.logs.push(`${godLabel(god)}刷新在了${tileName(tile)}`);}
function advanceTurn(state){if(state.ended)return state;for(const property of Object.values(state.properties))if(property.sealedTurns>0)property.sealedTurns-=1;const active=state.players.filter(p=>!p.eliminated);if(active.length<=1||state.round>state.maxRounds){state.ended=true;state.winnerId=[...active].sort((a,b)=>b.coins-a.coins)[0]?.peerId??null;return state;}const index=active.findIndex(p=>p.peerId===state.currentPlayerId),nextIndex=(index+1)%active.length;if(nextIndex===0){state.round+=1;state.godTokens=state.godTokens.filter(g=>g.expiresRound>state.round);if(state.round%2===0)spawnGod(state,Math.random);}state.currentPlayerId=active[nextIndex].peerId;const player=active[nextIndex];if(player.godTurns>0&&--player.godTurns===0)player.god=null;return state;}
function randomOf(seed){let v=Math.floor(seed)>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/0x100000000;};}
