const RANKS = [["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10],["J",11],["Q",12],["K",13],["A",14],["2",16]];
const SUITS = [{ suit:"spade", symbol:"♠", red:false },{ suit:"heart",symbol:"♥",red:true },{ suit:"club",symbol:"♣",red:false },{ suit:"diamond",symbol:"♦",red:true }];
export function createDeck() { const deck = []; for (const [rank,value] of RANKS) for (const suit of SUITS) deck.push({ id:`${rank}-${suit.suit}`,rank,value,...suit }); deck.push({id:"joker-small",rank:"SJ",label:"小王",symbol:"王",suit:"joker",value:17,red:true},{id:"joker-big",rank:"BJ",label:"大王",symbol:"王",suit:"joker",value:18,red:false}); return deck; }
export const sortCards = (cards) => [...cards].sort((a,b) => a.value-b.value || a.id.localeCompare(b.id));
export function shuffle(deck, seed = Date.now()) { const next=[...deck], random=seeded(seed); for(let i=next.length-1;i>0;i-=1){const j=Math.floor(random()*(i+1));[next[i],next[j]]=[next[j],next[i]];} return next; }
export function deal(peerIds, seed) { const deck=shuffle(createDeck(),seed), hands={}; peerIds.forEach((id)=>{hands[id]=sortCards(deck.splice(0,17));}); return {hands,landlordCards:sortCards(deck.splice(0,3))}; }
export function evaluate(cards) { const sorted=sortCards(cards), length=sorted.length; if(!length)return null; const grouped=new Map();for(const card of sorted)grouped.set(card.value,(grouped.get(card.value)??0)+1);const groups=[...grouped].map(([value,count])=>({value,count})).sort((a,b)=>a.value-b.value); const counts=groups.map(g=>g.count).sort((a,b)=>b-a), values=groups.map(g=>g.value); const info=(category,value,mainLength)=>({category,value,length,mainLength});
  if(length===1)return info("single",sorted[0].value); if(length===2&&sorted.every(c=>c.suit==="joker"))return info("rocket",99); if(length===2&&groups.length===1)return info("pair",groups[0].value); if(length===3&&groups.length===1)return info("triple",groups[0].value); if(length===4&&groups.length===1)return info("bomb",groups[0].value);
  if(length===4&&counts.join()==="3,1")return info("triple_single",groups.find(g=>g.count===3).value); if(length===5&&counts.join()==="3,2")return info("triple_pair",groups.find(g=>g.count===3).value);
  if(length>=5&&groups.every(g=>g.count===1)&&consecutive(values))return info("straight",values.at(-1),length); if(length>=6&&length%2===0&&groups.every(g=>g.count===2)&&consecutive(values))return info("double_straight",values.at(-1),length/2);
  const triples=groups.filter(g=>g.count===3).map(g=>g.value); if(triples.length>=2&&consecutive(triples)){const wings=length-triples.length*3,max=triples.at(-1);if(!wings)return info("airplane",max,triples.length);if(wings===triples.length)return info("airplane_single",max,triples.length);const rest=groups.filter(g=>!triples.includes(g.value));if(wings===triples.length*2&&rest.every(g=>g.count===2))return info("airplane_pair",max,triples.length);}
  if(length===6&&counts.join()==="4,1,1")return info("four_two_single",groups.find(g=>g.count===4).value); if(length===8&&counts.join()==="4,2,2"&&groups.filter(g=>g.count===2).length===2)return info("four_two_pair",groups.find(g=>g.count===4).value); return null;
}
export function canBeat(cards,last){const current=evaluate(cards);if(!current)return false;if(!last)return true;if(current.category==="rocket")return last.category!=="rocket";if(last.category==="rocket")return false;if(current.category==="bomb"&&last.category!=="bomb")return true;if(last.category==="bomb"&&current.category!=="bomb")return false;return current.category===last.category&&current.length===last.length&&current.mainLength===last.mainLength&&current.value>last.value;}
export const playLabel=(play)=>({single:"单牌",pair:"对子",triple:"三张",triple_single:"三带一",triple_pair:"三带二",straight:"顺子",double_straight:"连对",airplane:"飞机",airplane_single:"飞机带单",airplane_pair:"飞机带对",four_two_single:"四带二",four_two_pair:"四带两对",bomb:"炸弹",rocket:"王炸"}[play?.category]??"请选择合法牌型");
const consecutive=(values)=>values.length>0&&!values.some(v=>v>=16)&&values.every((v,i)=>i===0||v===values[i-1]+1); function seeded(seed){let v=Math.floor(seed)>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/0x100000000;};}
