import { createDeck, playLabel } from "./doudizhu.js"; import { applyEvent, createSession } from "./session.js";
const api=window.lanchat,$=id=>document.getElementById(id);let room=null,session=null,localPeerId=null,selected=new Set(),counter=0;
for(const[id,fn]of [["refreshRooms",refresh],["createRoom",createRoom],["readyButton",()=>send("doudizhu.ready",{ready:true})],["startButton",()=>send("doudizhu.start",{seed:Date.now()})],["bidButton",()=>send("doudizhu.bid",{call:true})],["noBidButton",()=>send("doudizhu.bid",{call:false})],["playButton",()=>send("doudizhu.play",{cardIds:[...selected]})],["passButton",()=>send("doudizhu.pass",{})],["restartButton",()=>send("doudizhu.restart",{})],["leaveButton",leave]])$(id).onclick=fn;
if(api){api.events.onPluginEnter(refresh);api.events.onRoomEvent(onEvent);api.events.onThemeChanged(theme);Promise.all([api.theme.current().then(theme),refresh()]).catch(report);}else $("statusText").textContent="请从 LanChat 插件中心打开";
async function refresh(){if(!api)return;const rooms=await api.rooms.list({gameId:"doudizhu"});$("roomList").replaceChildren(...rooms.map(roomCard));if(!rooms.length)$("roomList").textContent="还没有斗地主房间";}
function roomCard(value){const card=document.createElement("article"),copy=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("small"),button=document.createElement("button");title.textContent=value.name||"斗地主牌局";meta.textContent=`${value.memberPeerIds.length}/3 人`;copy.append(title,meta);button.textContent="加入";button.onclick=()=>join(value.roomId);card.append(copy,button);return card;}
async function createRoom(){room=await api.rooms.create({gameId:"doudizhu",name:$("roomName").value.trim()||"斗地主牌局",maxPlayers:3,schemaVersion:1});localPeerId=room.ownerPeerId;session=createSession(room.roomId,room.ownerPeerId,room.memberPeerIds);render();refresh();}
async function join(roomId){room=await api.rooms.join({roomId});localPeerId=room.memberPeerIds.at(-1);session=await api.rooms.snapshot({roomId}).catch(()=>null)||createSession(room.roomId,room.ownerPeerId,room.memberPeerIds);render();}
async function leave(){if(room)await api.rooms.leave({roomId:room.roomId});room=session=localPeerId=null;selected.clear();render();refresh();}
async function send(type,payload){if(room)await api.rooms.send({roomId:room.roomId,type,payload,idempotencyKey:`${room.roomId}-${Date.now()}-${counter+=1}`}).catch(report);}
function onEvent(event){if(!room||event.roomId!==room.roomId||event.gameId!=="doudizhu")return;session=applyEvent(session,event);selected.clear();render();if(session.phase==="ended")api.leaderboard.submit({gameId:"doudizhu",roomId:room.roomId,idempotencyKey:`${room.roomId}-result-${event.sequence}`,result:{winnerRole:session.winnerRole,landlordPeerId:session.landlordPeerId}}).catch(report);}
function render(){const hand=session?.hands?.[localPeerId]??[];$("roomMeta").textContent=room?`房间 ${room.roomId.slice(0,8)} · ${room.memberPeerIds.length}/3 人`:"尚未进入房间";$("statusText").textContent=!session?"创建或加入三人房间":session.phase==="lobby"?"等待三名玩家准备":session.phase==="bidding"?`等待 ${session.turnPeerId} 叫地主`:session.phase==="ended"?`${session.winnerRole==="landlord"?"地主":"农民"}获胜`:`轮到 ${session.turnPeerId}`;$("lastPlay").textContent=session?.lastPlay?`${playLabel(session.lastPlay)} · ${session.lastPlay.cards.map(c=>c.rank).join(" ")}`:"等待出牌";$("players").replaceChildren(...(session?.players??[]).map(p=>{const el=document.createElement("div");el.className=`player${p.peerId===session.turnPeerId?" active":""}`;el.textContent=`${p.role==="landlord"?"地主":"玩家"} ${p.peerId.slice(0,6)} · ${session.hands[p.peerId]?.length??17} 张`;return el;}));$("landlordCards").replaceChildren(...(session?.landlordCards??[]).map(cardElement));$("hand").replaceChildren(...(hand.length?hand:createDeck().slice(0,17).map(c=>({...c,hidden:true}))).map(cardElement));}
function cardElement(card){const b=document.createElement("button");b.className=`card${card.red?" red":""}${selected.has(card.id)?" selected":""}`;b.innerHTML=card.hidden?"<span>?</span>":`<strong>${card.rank}</strong><span>${card.symbol}</span>`;if(!card.hidden)b.onclick=()=>{selected.has(card.id)?selected.delete(card.id):selected.add(card.id);render();};return b;}
function theme(value){document.documentElement.dataset.theme=value.mode;for(const[k,v]of Object.entries(value.tokens??{}))document.documentElement.style.setProperty(`--${k}`,v);}function report(error){api?.logger.error("斗地主插件操作失败",{message:String(error)});api?.ui.notify({title:"斗地主",body:String(error),level:"error"});}render();
