import { canBeat, deal, evaluate, sortCards } from "./doudizhu.js";
export function createSession(roomId, ownerPeerId, memberPeerIds) { const peers=[...new Set(memberPeerIds)].slice(0,3); return {roomId,ownerPeerId,phase:"lobby",players:peers.map(peerId=>({peerId,ready:false,role:null})),hands:{},landlordCards:[],bidOrder:peers,bidIndex:0,bids:{},landlordPeerId:null,turnPeerId:null,lastPlay:null,passCount:0,winnerRole:null,appliedEventKeys:[]}; }
export function applyEvent(state,event){if(event.roomId!==state.roomId||event.gameId!=="doudizhu"||state.appliedEventKeys.includes(event.idempotencyKey))return state;let next=state;const player=state.players.find(p=>p.peerId===event.senderPeerId);
  if(event.type==="doudizhu.ready"&&state.phase==="lobby"&&player)next={...state,players:state.players.map(p=>p.peerId===player.peerId?{...p,ready:event.payload?.ready===true}:p)};
  else if(event.type==="doudizhu.start"&&event.senderPeerId===state.ownerPeerId&&state.players.length===3&&state.players.every(p=>p.ready)){const cards=deal(state.players.map(p=>p.peerId),event.payload?.seed??Date.now());next={...state,phase:"bidding",hands:cards.hands,landlordCards:cards.landlordCards,bidOrder:state.players.map(p=>p.peerId),bidIndex:0,bids:{},turnPeerId:state.players[0].peerId,lastPlay:null,passCount:0,winnerRole:null};}
  else if(event.type==="doudizhu.bid"&&state.phase==="bidding"&&state.bidOrder[state.bidIndex]===event.senderPeerId){const bids={...state.bids,[event.senderPeerId]:event.payload?.call===true},bidIndex=state.bidIndex+1;if(bidIndex<state.bidOrder.length)next={...state,bids,bidIndex,turnPeerId:state.bidOrder[bidIndex]};else{const landlord=state.bidOrder.find(id=>bids[id])??state.bidOrder[0];next={...state,bids,bidIndex,phase:"playing",landlordPeerId:landlord,turnPeerId:landlord,players:state.players.map(p=>({...p,role:p.peerId===landlord?"landlord":"farmer"})),hands:{...state.hands,[landlord]:sortCards([...state.hands[landlord],...state.landlordCards])}};}}
  else if(event.type==="doudizhu.play"&&state.phase==="playing"&&state.turnPeerId===event.senderPeerId&&player){const ids=[...new Set(event.payload?.cardIds??[])],hand=state.hands[player.peerId]??[],cards=ids.map(id=>hand.find(c=>c.id===id)).filter(Boolean);if(cards.length!==ids.length||!canBeat(cards,state.lastPlay))return state;const info=evaluate(cards),remaining=hand.filter(c=>!ids.includes(c.id)),winnerRole=remaining.length===0?player.role:null;next={...state,hands:{...state.hands,[player.peerId]:remaining},lastPlay:{...info,playerId:player.peerId,cards},passCount:0,turnPeerId:nextPeer(state,player.peerId),phase:winnerRole?"ended":"playing",winnerRole};}
  else if(event.type==="doudizhu.pass"&&state.phase==="playing"&&state.turnPeerId===event.senderPeerId&&state.lastPlay){const passCount=state.passCount+1;next={...state,passCount,turnPeerId:nextPeer(state,event.senderPeerId),lastPlay:passCount>=2?null:state.lastPlay};}
  else if(event.type==="doudizhu.restart"&&state.phase==="ended"&&event.senderPeerId===state.ownerPeerId)next=createSession(state.roomId,state.ownerPeerId,state.players.map(p=>p.peerId));else return state;
  return{...next,appliedEventKeys:[...state.appliedEventKeys,event.idempotencyKey].slice(-1024)};}
const nextPeer=(state,id)=>{const i=state.players.findIndex(p=>p.peerId===id);return state.players[(i+1)%state.players.length]?.peerId??null;};
