import { cp, mkdir, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(join(root, "public", "index.html"), join(dist, "index.html"));
for (const file of ["main.js", "xiangqi.js", "session.js", "styles.css"]) await cp(join(root, "src", file), join(dist, file));
console.log(`象棋插件已构建: ${dist}`);
